### ISSUE TITLE
Update developer photo

### ISSUE THREAD

**Issue by edmondthui** [edmondthui/partyr#99]
Update the source for your developer photo.

**Comment by edmondthui** [comment]
updated

**Comment by edmondthui** [comment]
Use the i.imgur link if you're using Imgur. The photo still not working.

**Comment by bigcachemoney** [comment]
Updated my photo url with `https://i.imgur.com/sM9rzDl.jpg`. I tested it on the browser, should work.

**Comment by edmondthui** [comment]
Issue solved
